# fly.toml app configuration file generated for atlas-backend-api on 2025-05-31T17:48:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atlas-backend-api'
primary_region = 'bom'

[build]

[processes]
  app = "sh -c 'gunicorn api:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 2 --timeout 0 --access-logfile - --error-logfile -'"
  worker = "python -m dramatiq run_agent_background"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# API server VM configuration
[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
  processes = ['app']

# Worker VM configuration
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  processes = ['worker']
